# https://gohugo.io/getting-started/configuration/#toml-configuration

# ##################################################
# Hugo-defined variables
# set params.uglyURLs false (see below)
#baseURL       = "https://it-gro.github.io/hugo-theme-w3css-basic.github.io"
baseURL       = "http://example.com"
#default:
#relativeURLs  = false
#uglyURLs      = false

# config for local filesystem destination (no webserver):
# set params.uglyURLs true (see below)
#baseURL       = ""
#relativeURLs  = true
#uglyURLs      = true 


title         = "hugo-theme-w3css-basic exampleSite"
#languageCode  = "de-ch"
languageCode  = "en-us"
theme         = "hugo-theme-w3css-basic"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Pagination (3,6,9,12, ...)
paginate =  6

# https://help.farbox.com/pygments.html
pygmentsUseClassic            = false
pygmentsCodeFences            = true
pygmentsCodeFencesGuessSyntax = true
# https://github.com/alecthomas/chroma
# hugo gen chromastyles -h
# hugo gen chromastyles > syntax.css
# hugo gen chromastyles --style=monokai > syntax.css
pygmentsUseClasses            = true
# => static/css/syntax/syntax/syntax.*.css
# copy one of them to
# static/css/syntax/syntax.css
# alternative (if shortcodes/csc*.html are not used):
# set pygmentsUseClassic to false on choose one of the following:
#pygmentsStyle = "autumn"
#pygmentsStyle = "borland"
#pygmentsStyle = "bw"
#pygmentsStyle = "colorful"
#pygmentsStyle = "default"
#pygmentsStyle = "emacs"
#pygmentsStyle = "friendly"
#pygmentsStyle = "fruity"
#pygmentsStyle = "manni"
#pygmentsStyle = "monokai"
#pygmentsStyle = "murphy"
#pygmentsStyle = "native"
#pygmentsStyle = "pastie"
#pygmentsStyle = "perldoc"
#pygmentsStyle = "rrt"
#pygmentsStyle = "tango"
#pygmentsStyle = "trac"
#pygmentsStyle = "vim"
#pygmentsStyle = "vs"


# ##################################################
# Theme-defined configuration

# ToDo
# Enable comments by entering your Disqus shortname
disqusShortname = ""


# ##################################################
# hugo sections

[taxonomies]
  tag = "tags"
  category = "categories"
  test     = "tests"

[Permalinks]
  blog = "/blog/:year/:month/:day/:filename/"


# Main menu
[menu]

[[menu.main]]
  weight = 1
  name   = "Home"
  url    = "/index.html"
  pre    = "fa fa-home"

[[menu.main]]
  weight = 2
  name   = "Contact"
  url    = "/contact"
  pre    = "fa fa-id-card-o"

[[menu.main]]
  weight = 3
  name   = "Pages"
  url    = "/pages"
  pre    = "fa fa-list"

# demo submenu
#[[menu.main]]
#  weight = 4
#  name   = "Posts"
#  identifier = "posts"
#
#[[menu.main]]
#  weight = 1
#  name   = "News"
#  url    = "/news/"
#  parent = "posts"
#
#[[menu.main]]
#  weight = 2
#  name   = "Blog"
#  url    = "/blog/"
#  parent = "posts"

[[menu.main]]
  weight = 4
  name   = "Blog"
  url    = "/blog"
  pre    = "fa fa-rss"

[[menu.main]]
  weight = 5
  name   = "FAQ"
  url    = "/faq"
  pre    = "fa fa-question-circle-o"


# right aligned
[[menu.topbar]]
  weight   = 1
  name     = "GitHub"
  url      = "https://github.com/it-gro/hugo-theme-w3css-basic"
  pre      = "fa fa-github"

#[[menu.topbar]]
#  weight   = 2
#  name     = "Facebook"
#  url      = "http://facebook.com"
#  pre      = "fa fa-facebook"

#[[menu.topbar]]
#  weight   = 3
#  name     = "Twitter"
#  url      = "http://twitter.com"
#  pre      = "fa fa-twitter"

[[menu.topbar]]
  weight   = 4
  name     = "Email"
  url      = "#address"
# url      = "mailto:info@example.com"
  pre      = "fa fa-envelope"

[[menu.topbar]]
  weight   = 5
  name     = "Search"
  url      = "/search"
  pre      = "fa fa-search"

# if google translate is not an option, provide multilingual menu
# https://gohugo.io/content-management/multilingual/
#
# [languages.en]
# weight = 0
# languageName = "English"
#
# [[languages.en.menu.main]]
#   weight = 1
#   name   = "Home"
#   url    = "/index.html"
#
# [[languages.en.menu.main]]
#   weight = 2
#   name   = "Contact"
#   url    = "/contact"
#
# [[languages.en.menu.main]]
#   weight = 3
#   name   = "Pages"
#   url    = "/pages"
#
# [[languages.en.menu.main]]
#   weight = 4
#   name   = "Posts"
#   identifier = "posts"
#
# [[languages.en.menu.main]]
#   weight = 1
#   name   = "News"
#   url    = "/news"
#   parent = "posts"
#
# [[languages.en.menu.main]]
#   weight = 2
#   name   = "Blog"
#   url    = "/blog"
#   parent = "posts"
#
# [[languages.en.menu.main]]
#   weight = 5
#   name   = "FAQ"
#   url    = "/faq"
#
# [languages.de]
# weight = 010
# languageName = "Deutsch"
#
# [[languages.de.menu.main]]
#   weight = 1
#   name   = "Home"
#   url    = "/index.html"
#
# [[languages.de.menu.main]]
#   weight = 2
#   name   = "Kontakt"
#   url    = "/contact"
#
# [[languages.de.menu.main]]
#   weight = 3
#   name   = "Seiten"
#   url    = "/pages"
#
# [[languages.de.menu.main]]
#   weight = 4
#   name   = "Posts"
#   identifier = "posts"
#
# [[languages.de.menu.main]]
#   weight = 1
#   name   = "News"
#   url    = "/news"
#   parent = "posts"
#
# [[languages.de.menu.main]]
#   weight = 2
#   name   = "Blog"
#   url    = "/blog"
#   parent = "posts"
#
# [[languages.de.menu.main]]
#   weight = 5
#   name   = "FAQ"
#   url    = "/faq"

# Top bar social links menu

# ToDo:
#  https://gohugo.io/content-management/menus/
#  > if you make use of the multilingual feature, you can define language-independent menus.
#  how?

# [[languages.en.menu.topbar]]
#   weight = 1
#   name   = "GitHub"
#   url    = "https://github.com/it-gro/hugo-theme-w3css-basic"
#   pre   = "fa fa-github"
#
# [[languages.en.menu.topbar]]
#   weight = 2
#   name   = "Facebook"
#   url    = "http://facebook.com"
#   pre   = "fa fa-facebook"
#
# [[languages.en.menu.topbar]]
#   weight = 3
#   name   = "Twitter"
#   url    = "http://twitter.com"
#   pre   = "fa fa-twitter"
#
# [[languages.en.menu.topbar]]
#   weight = 4
#   name   = "Email"
#   url    = "#footer"
# # url    = "mailto:info@example.com"
#   pre   = "fa fa-envelope"
#
# [[languages.de.menu.topbar]]
#   weight = 1
#   name   = "GitHub"
#   url    = "https://github.com/it-gro/hugo-theme-w3css-basic"
#   pre   = "fa fa-github"
#
# [[languages.de.menu.topbar]]
#   weight = 2
#   name   = "Facebook"
#   url    = "http://facebook.com"
#   pre   = "fa fa-facebook"
#
# [[languages.de.menu.topbar]]
#   weight = 3
#   name   = "Twitter"
#   url    = "http://twitter.com"
#   pre   = "fa fa-twitter"
#
# [[languages.de.menu.topbar]]
#   weight = 4
#   name   = "Email"
#   url    = "#footer"
# # url    = "mailto:info@example.com"
#   pre   = "fa fa-envelope"



# ##################################################
# theme-defined params
[params]

  debug              = false
  uglyURLs           = false
  uglyUrl            = ".html"

  # used in layouts/partials/head.meta.html
  authorName         = "it-gro"
  defaultKeywords    = ["foo", "bar"]
  defaultDescription = "example site created with hugo using theme hugo-theme-w3css-basic"

  # used in layouts/partials/head.stylesheets.html
  # set W3.CSS color theme (choose one)
  #w3cssColorTheme = "/css/w3-theme-custom.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-amber.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-black.css"
  w3cssColorTheme = "/vendor/w3css/4/w3-theme-blue-grey.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-blue.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-brown.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-cyan.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-dark-grey.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-deep-orange.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-deep-purple.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-green.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-grey.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-indigo.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-khaki.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-light-blue.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-light-green.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-lime.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-orange.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-pink.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-purple.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-red.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-teal.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-yellow.css"


  # Google Maps API key
  # get our own: https://developers.google.com/maps/documentation/javascript/adding-a-google-map#key
  # used in layouts/partials/contact.map.html
  # if empty => fallback to URL (instead of map)
  # define environment variable (=> key ist not stored in github)
  envGoogleMapsApiKey = "GoogleMapsApiKey"
  #googleMapsZoom   = 14
  googleMapsZoom   = 3
  latitude         = 46.946692
  longitude        =  7.444186

  # if environment is not an option => define key here:
  #googleMapsApiKey = ""


  # https://gohugo.io/functions/truncate/
  # used in layouts/pages/list.html
  #         layouts/partials/front.recent_posts.html
  #         layouts/partials/main.teaser_in_card.html
  teaserTruncateSummary  = 200


  # multiple lines in toml
  # https://github.com/toml-lang/toml#user-content-string

  # used in layouts/partials/footer.html
  # uses markdownify
  aboutUs   = '''
Vel illum **dolore** eu      
                             
  * feugiat nulla            
  * facilisis at vero.       
              '''

  address   = '''
**nobis eleifend**             
**Soluta nobis eleifend**      
illum dolore eu feugiat        
3612 Steffisburg               
consectetuer adipiscing        

**Switzerland**
              '''

  # used in layouts/partials/footer.bottom.html
  bottomLeft  = "Copyright (c) 2017, *lobortis nisl* ut aliquip ex ea commodo consequat"
  bottomRight = 'created with [Hugo](https://gohugo.io) '


  # used in partials/contact.form.html
  #
  # Since this template is static, the contact form uses www.formspree.io as a
  # proxy. The form makes a POST request to their servers to send the actual
  # email. Visitors can send up to a 1000 emails each month for free.
  #
  # What you need to do for the setup?
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email yourself to confirm your account
  # - click the confirm link in the email from www.formspree.io
  # - you're done. Happy mailing!
  #
  #Â Enable the contact form by entering your Formspree.io email
  formspree = "formspree.io"
  email     = "info@example.com"

  # Format dates with Go's time formatting
  # used in layouts/taxonomy/_category.html
  #         layouts/taxonomy/_tag.html
  #         layouts/partials/main.teaser_in_card.html
  #date_format = "January 2, 2006"
  #date_format = "January 2 15:04:05 2006 MST"
  #date_format = "Jan 2 15:04:05 2006 MST"
  #date_format = "Jan 2 15:04:05 2006 -7"
  #date_format = "2006.01.02"
  date_format = "01.02.2006"



# ##################################################
# more theme defined params

[params.marquee]
  # enable or disable marquee on frontpage
  enable   = true
 #enable   = false
  marquee  = '''
At [info@example.com](mailto:info@example.com) vero eos et **accusam**
et justo duo dolores et ea rebum. Stet clita *kasd gubergren*, no sea
             '''

[params.menuTopBar]
  # used in layouts/partials/header.nav.html
  # enable or disable menu.topbar with social icons (right aligned)
  socialEnable             = true
  numOfItemsIfSmallDisplay = 1
  googleTranslateEnable    = true

[params.jumbotrons]
  # used in layouts/partials/front.jumbotrons.carousel.html
  # enable or disable jumbotrons on frontpage
  # see some examples in 'exampleSite/data/jumbotron'
  enable   = true
  #enable   = false

[params.photocards]
  # used in layouts/partials/front.photocards.html
  # enable or disable photocards on frontpage
  # see some examples in 'exampleSite/data/photocards'
  #enable  = false
  enable   = true
  limitTo  = 3
  #limitTo  = 6

[params.features]
  # used in layouts/partials/front.features.html
  # enable or disable features on frontpage
  # see some examples in 'exampleSite/data/features'
  #enable  = false
  enable   = true
  limitTo  = 3
  #limitTo  = 6

[params.testimonials]
  # used in layouts/partials/front.testimonials.carousel.html
  # enable or disable testimonials on frontpage
  # see some examples in 'exampleSite/data/testimonials'
  enable   = true
  #enable  = false
  title    = "Testimonials"
  subtitle = '''
Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut
labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos
et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
             '''

[params.seeMore]
  # used in layouts/partials/front.see_more.html
  # enable or disable see_more on frontpage
  enable    = true
 #enable    = false
  icon      = "fa fa-file-code-o"
  title     = "Do You want to see More?"
  linkUrl   = "/pages"
  linkText  = "consectetuer adipiscing"
  subtitle  = '''
Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper
suscipit lobortis nisl ut aliquip ex ea commodo consequat.
              '''

[params.clients]
  # used in layouts/partials/front.clients.carousel.html
  # enable or disable clients on frontpage
  # see some examples in 'exampleSite/data/clients'
  enable = true
  #enable = false
  # All clients are defined in their own files. You can find example items
  # at 'exampleSite/data/clients'.
  # For more informtion take a look at the README.
  title = "Our Clients"
  subtitle = '''
Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse
**molestie consequat**, vel illum dolore eu feugiat nulla facilisis at
vero eros et accumsan et iusto odio dignissim qui blandit praesent
luptatum zzril delenit augue duis dolore te feugait nulla
facilisi.
             '''

[params.recentPosts]
  # used in layouts/partials/footer.html
  footerNumOfPosts = 5
  enableFooter   = true
  # used in layouts/partials/front.recent_posts.html
  enableFront    = true
  #enable = false
  title    = "From our Blog"
  subtitle = '''
Pellentesque habitant morbi tristique senectus et netus et malesuada
fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,
ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam
egestas semper. Aenean ultricies mi vitae est. Mauris placerat
eleifend leo.
             '''

[params.blog]
  # used in layouts/blog/list.html
  subtitle = '''
ultricies eget, tempor sit amet, ante
             '''

# ##################################################
[blackfriday]
  #extensions = ["hardLineBreak"]
  # https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
  # http://commonmark.org/
  # http://spec.commonmark.org/0.28/

# emacs
# Local variables:
# tab-width:        2
# indent-tabs-mode: nil
# End:
